#
# System settings
#
SYSTEM_TIMEZONE=EST

#
# Software releases (non package managed)
#
SPRUCE_RELEASE_VERSION=1.27.0
JQ_RELEASE_VERSION=1.6
TERRAFORM_RELEASE_VERSION=1.0.11
TERRAFORM_TEST_RELEASE_VERSION=1.1.7
CF_CLI_RELEASE_VERSION6=6.53.0
CF_CLI_RELEASE_VERSION7=7.2.0
CREDHUB_CLI_RELEASE_VERSION=2.8.0
# bosh-cli gets really slow at 6.2.0, so we're pinned here.
# check https://github.com/cloudfoundry/bosh-cli/issues/570 for details
BOSH_CLI_V2_RELEASE_VERSION=6.1.1
UAAC_CLI_RELEASE_VERSION=4.2.0
CONCOURSE_CLI_RELEASE_VERSION=6.7.1

#
# Command versions (only for testing purposes)
#
MAKE_CMD_VERSION=4.1
CMAKE_CMD_VERSION=3.10.2
RAKE_CMD_VERSION=12.3.1
RUBY_CMD_VERSION=2.5.1p57
GEM_CMD_VERSION=2.7.6
UNZIP_CMD_VERSION=6.00
CURL_CMD_VERSION=7.58.0
GIT_CMD_VERSION=2.17.1
JQ_CMD_VERSION=jq-1.6
TERRAFORM_CMD_VERSION=v0.2.3
CF_CMD_VERSION=7.2.0
UAAC_CMD_VERSION=4.2.0
BATS_CMD_VERSION=0.4.0
